import os
import sys
import threading
import tkinter as tk
from tkinter import filedialog, messagebox, ttk

try:
    import fitz  # PyMuPDF
except ImportError:
    import tkinter.messagebox as mb
    root = tk.Tk()
    root.withdraw()
    mb.showerror("Error", "PyMuPDF is missing. Please run 'pip install PyMuPDF' from the command line.")
    sys.exit(1)

RENDER_ZOOM = 4.0
JPEG_QUALITY = 92
GENERATED_STATIC_FILES = {"index.html", "style.css", "script.js"}


def is_generated_page_image(file_name):
    stem, ext = os.path.splitext(file_name)
    return ext.lower() == ".jpg" and stem.startswith("page_") and stem[5:].isdigit()


def clean_generated_outputs(output_dir):
    if not os.path.isdir(output_dir):
        return

    for entry_name in os.listdir(output_dir):
        entry_path = os.path.join(output_dir, entry_name)
        if not os.path.isfile(entry_path):
            continue
        if entry_name in GENERATED_STATIC_FILES or is_generated_page_image(entry_name):
            os.remove(entry_path)


APP_NAME = "PDF Flipbook Generator"
DEFAULT_LANGUAGE = "en"

TRANSLATIONS = {
    "en": {
        "language_name": "English",
        "language_label": "Language:",
        "no_pdf_selected": "No PDF selected yet.",
        "select_file": "1. Select File",
        "start": "2. Start",
        "file_dialog_title": "Select a PDF for PDF Flipbook Generator",
        "file_type_pdf": "PDF files",
        "selected_file": "Selected: {file_name}",
        "starting": "Starting...",
        "loading_pdf": "Loading PDF...",
        "pages_found": "{page_count} pages found. Processing...",
        "converting_page": "Converting page {current}/{total}...",
        "creating_files": "Creating flipbook files (HTML/CSS/JS)...",
        "done": "Done!",
        "generic_error": "An error occurred.",
        "conversion_complete": "Conversion complete! Folder: {folder_name}",
        "success_title": "Success",
        "success_message": "Your flipbook was created successfully!\nOpen index.html in the generated folder with any browser.",
        "error_title": "Error",
        "conversion_error": "A critical error occurred while converting the PDF:\n\n{error}",
        "html_lang": "en",
        "meta_description": "{title} flipbook generated by PDF Flipbook Generator.",
        "previous_page": "Previous Page",
        "next_page": "Next Page",
        "zoom_out": "Zoom Out",
        "zoom_in": "Zoom In",
        "pages": "Pages",
        "page_word": "Page",
    },
    "tr": {
        "language_name": "Türkçe",
        "language_label": "Dil:",
        "no_pdf_selected": "Henüz bir PDF seçilmedi.",
        "select_file": "1. Dosya Seç",
        "start": "2. Başlat",
        "file_dialog_title": "PDF Flipbook Generator için PDF seçin",
        "file_type_pdf": "PDF dosyaları",
        "selected_file": "Seçilen: {file_name}",
        "starting": "Başlatılıyor...",
        "loading_pdf": "PDF yükleniyor...",
        "pages_found": "{page_count} sayfa bulundu. İşleniyor...",
        "converting_page": "Sayfa {current}/{total} dönüştürülüyor...",
        "creating_files": "Flipbook dosyaları oluşturuluyor (HTML/CSS/JS)...",
        "done": "Tamamlandı!",
        "generic_error": "Bir hata oluştu.",
        "conversion_complete": "Dönüştürme tamamlandı! Klasör: {folder_name}",
        "success_title": "Başarılı",
        "success_message": "Flipbook başarıyla oluşturuldu!\nOluşturulan klasördeki index.html dosyasını herhangi bir tarayıcıda açabilirsiniz.",
        "error_title": "Hata",
        "conversion_error": "PDF dönüştürülürken kritik bir hata oluştu:\n\n{error}",
        "html_lang": "tr",
        "meta_description": "{title} PDF Flipbook Generator ile oluşturulmuş flipbook.",
        "previous_page": "Önceki Sayfa",
        "next_page": "Sonraki Sayfa",
        "zoom_out": "Uzaklaştır",
        "zoom_in": "Yakınlaştır",
        "pages": "Sayfalar",
        "page_word": "Sayfa",
    },
}


def get_texts(language):
    return TRANSLATIONS.get(language, TRANSLATIONS[DEFAULT_LANGUAGE])


class PDFFlipbookGeneratorApp:
    def __init__(self, root):
        self.root = root
        self.root.title(APP_NAME)
        self.root.geometry("450x285")
        self.root.configure(padx=20, pady=20)
        self.root.resizable(False, False)
        
        self.pdf_path = None
        self.is_running = False
        self.language_var = tk.StringVar(value=DEFAULT_LANGUAGE)
        self.language_options = {
            texts["language_name"]: code
            for code, texts in TRANSLATIONS.items()
        }
        
        # UI elements
        self.lbl_title = tk.Label(root, text=APP_NAME, font=("Segoe UI", 14, "bold"))
        self.lbl_title.pack(pady=(0, 12))

        frame_language = tk.Frame(root)
        frame_language.pack(pady=(0, 12))

        self.lbl_language = tk.Label(frame_language)
        self.lbl_language.grid(row=0, column=0, padx=(0, 8))

        self.cmb_language = ttk.Combobox(
            frame_language,
            state="readonly",
            width=15,
            values=list(self.language_options.keys()),
        )
        self.cmb_language.grid(row=0, column=1)
        self.cmb_language.set(TRANSLATIONS[DEFAULT_LANGUAGE]["language_name"])
        self.cmb_language.bind("<<ComboboxSelected>>", self.change_language)
        
        self.lbl_file = tk.Label(root, fg="gray")
        self.lbl_file.pack(pady=(0, 10))
        
        frame_btns = tk.Frame(root)
        frame_btns.pack(pady=10)
        
        self.btn_select = tk.Button(frame_btns, command=self.select_file, width=15)
        self.btn_select.grid(row=0, column=0, padx=5)
        
        self.btn_start = tk.Button(frame_btns, command=self.start_conversion, width=15, state=tk.DISABLED)
        self.btn_start.grid(row=0, column=1, padx=5)
        
        self.lbl_status = tk.Label(root, text="")
        self.lbl_status.pack(pady=(10, 5))
        
        self.progress = ttk.Progressbar(root, orient="horizontal", length=400, mode="determinate")
        self.progress.pack()
        self.update_ui_texts()

    def texts(self):
        return get_texts(self.language_var.get())

    def change_language(self, _event=None):
        selected_name = self.cmb_language.get()
        self.language_var.set(self.language_options.get(selected_name, DEFAULT_LANGUAGE))
        self.update_ui_texts()

    def update_ui_texts(self):
        texts = self.texts()
        self.lbl_language.config(text=texts["language_label"])
        self.btn_select.config(text=texts["select_file"])
        self.btn_start.config(text=texts["start"])
        if self.pdf_path:
            short_name = os.path.basename(self.pdf_path)
            if len(short_name) > 40:
                short_name = short_name[:37] + "..."
            self.lbl_file.config(text=texts["selected_file"].format(file_name=short_name), fg="black")
        else:
            self.lbl_file.config(text=texts["no_pdf_selected"], fg="gray")

    def select_file(self):
        texts = self.texts()
        file_path = filedialog.askopenfilename(
            title=texts["file_dialog_title"],
            filetypes=[(texts["file_type_pdf"], "*.pdf")]
        )
        if file_path:
            self.pdf_path = file_path
            short_name = os.path.basename(file_path)
            if len(short_name) > 40:
                short_name = short_name[:37] + "..."
            self.lbl_file.config(text=texts["selected_file"].format(file_name=short_name), fg="black")
            self.btn_start.config(state=tk.NORMAL)

    def start_conversion(self):
        if not self.pdf_path: return
        self.is_running = True
        self.active_language = self.language_var.get()
        self.btn_select.config(state=tk.DISABLED)
        self.btn_start.config(state=tk.DISABLED)
        self.cmb_language.config(state=tk.DISABLED)
        self.progress['value'] = 0
        self.lbl_status.config(text=get_texts(self.active_language)["starting"])
        
        # Run in the background to keep the UI responsive.
        threading.Thread(target=self.process_pdf, daemon=True).start()

    def update_progress(self, val, text):
        self.progress['value'] = val
        self.lbl_status.config(text=text)

    def process_pdf(self):
        language = getattr(self, "active_language", DEFAULT_LANGUAGE)
        texts = get_texts(language)
        try:
            base_name = os.path.splitext(os.path.basename(self.pdf_path))[0]
            output_dir = os.path.join(os.path.dirname(self.pdf_path), f"{base_name}_flipbook")
            
            os.makedirs(output_dir, exist_ok=True)
            clean_generated_outputs(output_dir)
            self.root.after(0, self.update_progress, 0, texts["loading_pdf"])
            
            doc = fitz.open(self.pdf_path)
            try:
                page_count = len(doc)
                
                self.root.after(0, self.update_progress, 5, texts["pages_found"].format(page_count=page_count))
                
                page0 = doc.load_page(0)
                w = page0.rect.width
                h = page0.rect.height
                # A single-page PDF should keep the original page aspect ratio.
                is_single_page = page_count == 1
                calculated_aspect_ratio = (w / h) if is_single_page else (w * 2) / h
                # High-resolution rendering for sharp page images.
                zoom = RENDER_ZOOM
                mat = fitz.Matrix(zoom, zoom)
                images = []
                
                for i in range(page_count):
                    page = doc.load_page(i)
                    pix = page.get_pixmap(matrix=mat)
                    
                    img_name = f"page_{i+1}.jpg"
                    img_path = os.path.join(output_dir, img_name)
                    pix.save(img_path, jpg_quality=JPEG_QUALITY)
                    pix = None
                    images.append(img_name)
                    
                    # Keep conversion progress within the 5%-95% range.
                    progress_val = 5 + (90 * (i + 1) / page_count)
                    self.root.after(
                        0,
                        self.update_progress,
                        progress_val,
                        texts["converting_page"].format(current=i + 1, total=page_count),
                    )
            finally:
                doc.close()

            self.root.after(0, self.update_progress, 98, texts["creating_files"])
            create_static_assets(output_dir, images, base_name, calculated_aspect_ratio, page_count, language)
            
            self.root.after(0, self.update_progress, 100, texts["done"])
            self.root.after(0, self.finish_success, output_dir)
            
        except Exception as e:
            self.root.after(0, self.show_error, str(e))
            self.root.after(0, self.reset_ui, texts["generic_error"])

    def reset_ui(self, msg):
        self.is_running = False
        self.lbl_status.config(text=msg)
        self.btn_select.config(state=tk.NORMAL)
        self.btn_start.config(state=tk.NORMAL if self.pdf_path else tk.DISABLED)
        self.cmb_language.config(state="readonly")

    def finish_success(self, output_dir):
        texts = get_texts(getattr(self, "active_language", self.language_var.get()))
        self.reset_ui(texts["conversion_complete"].format(folder_name=os.path.basename(output_dir)))
        messagebox.showinfo(texts["success_title"], texts["success_message"])
        if os.name == 'nt':
            os.startfile(output_dir)

    def show_error(self, err_msg):
        texts = get_texts(getattr(self, "active_language", self.language_var.get()))
        messagebox.showerror(texts["error_title"], texts["conversion_error"].format(error=err_msg))

def create_static_assets(output_dir, images, title, aspect_ratio, page_count, language=DEFAULT_LANGUAGE):
    texts = get_texts(language)
    # HTML content
    html_content = f"""<!DOCTYPE html>
<html lang="{texts['html_lang']}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>{title} - PDF Flipbook Generator</title>
    <meta name="description" content="{texts['meta_description'].format(title=title)}">
    <link rel="stylesheet" href="style.css">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
</head>
<body>
    <div class="book-container">
        <div class="book">
"""
    
    # Group pages into leaves. Each leaf has a front and a back side.
    leaves_count = (len(images) + 1) // 2
    
    for i in range(leaves_count):
        front_img = images[i * 2]
        back_img = images[i * 2 + 1] if (i * 2 + 1) < len(images) else ""
        
        back_style = f"background-image: url('{back_img}');" if back_img else "background-color: #f4f4f4;"
        
        html_content += f"""            <div class="leaf">
                <div class="front" style="background-image: url('{front_img}');"></div>
                <div class="back" style="{back_style}"></div>
            </div>\n"""

    html_content += f"""        </div>
        <!-- Previous and next navigation buttons -->
        <button id="prevBtn" class="nav-btn nav-btn-left" title="{texts['previous_page']}">&#9664;</button>
        <button id="nextBtn" class="nav-btn nav-btn-right" title="{texts['next_page']}">&#9654;</button>
        <!-- Pill-shaped zoom controls -->
        <div class="zoom-controls-pill">
            <button id="zoomOutBtn" class="zoom-btn" title="{texts['zoom_out']}">&minus;</button>
            <div class="zoom-divider"></div>
            <button id="zoomInBtn" class="zoom-btn" title="{texts['zoom_in']}">+</button>
        </div>
        
        <!-- Page menu toggle -->
        <button id="menuToggleBtn" class="menu-toggle-btn" title="{texts['pages']}">
            <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
        </button>
        
        <!-- Collapsible page slider menu -->
        <div class="slider-menu-container" id="sliderMenu">
            <div class="slider-menu-content">
                <span id="pageIndicator" class="page-indicator">1 / {page_count}</span>
                <div class="slider-wrapper">
                    <input type="range" id="pageSlider" min="0" max="{page_count}" value="0" step="1">
                </div>
            </div>
        </div>
    </div>
    <script src="script.js"></script>
</body>
</html>"""

    # CSS content
    css_content = """body {
    margin: 0;
    padding: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100dvh;
    background: linear-gradient(135deg, #f2f3f2, #e5e6e5);
    font-family: 'Inter', sans-serif;
    color: #2c3e50;
    overflow: hidden;
    touch-action: none; /* Disable native Safari/iOS scrolling so JS can control gestures. */
}

.book-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
}

.book-title {
    margin-bottom: 2rem;
    font-weight: 600;
    font-size: 1.5rem;
    letter-spacing: 1px;
    opacity: 0.9;
}

.book {
    position: relative;
    /* Fit the PDF at the largest possible size without changing its aspect ratio. */
    width: 95vw;
    height: auto;
    max-width: calc((100dvh - 130px) * ASPECT_RATIO_PLACEHOLDER);
    aspect-ratio: ASPECT_RATIO_PLACEHOLDER; /* Dynamic PDF page aspect ratio */
    perspective: 2000px; /* 3D depth */
}

.book::before, .book::after {
    content: "";
    position: absolute;
    top: 0; width: 50%; height: 100%;
    background-color: #ffffff;
    box-shadow: 0 15px 40px rgba(0,0,0,0.1);
    z-index: -1;
    transition: opacity 0.4s ease;
}

.book::before { left: 0; border-radius: 5px 0 0 5px; }
.book::after { right: 0; border-radius: 0 5px 5px 0; }

/* Hide the left white cover when the book is closed. */
.book:not(:has(.leaf.flipped))::before {
    opacity: 0;
}

/* Hide the right white cover at the end of the book. */
.book:not(:has(.leaf:not(.flipped)))::after {
    opacity: 0;
}

/* Soften shadows on mobile without changing the book aspect ratio. */
@media (max-width: 768px) {
    .book::before, .book::after {
        box-shadow: 0 8px 20px rgba(0,0,0,0.08);
    }
}

/* Mobile landscape optimization */
@media (max-height: 500px) and (orientation: landscape) {
    .zoom-controls-pill {
        bottom: 10px;
        left: 10px;
        padding: 0;
    }
    .menu-toggle-btn {
        bottom: 10px;
        right: 10px;
        width: 44px;
        height: 44px;
    }
    .slider-menu-container {
        bottom: 65px;
        right: 10px;
    }
    .zoom-btn {
        width: 32px;
        height: 32px;
        font-size: 1.4rem;
        padding-bottom: 2px;
    }
    .page-indicator {
        font-size: 0.85rem;
        padding: 4px 8px;
    }
    .book {
        max-width: calc((100dvh - 85px) * ASPECT_RATIO_PLACEHOLDER);
    }
    .nav-btn {
        height: 50px;
        bottom: 60px;
    }
}

.leaf {
    position: absolute;
    top: 0;
    right: 0;
    width: 50%;
    height: 100%;
    transform-origin: left center;
    transform-style: preserve-3d;
    transition: transform 0.8s cubic-bezier(0.645, 0.045, 0.355, 1);
    cursor: pointer;
}

.front, .back {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    backface-visibility: hidden;
    background-size: 100% 100%;
    background-position: center;
    background-repeat: no-repeat;
    background-color: #ffffff;
    box-shadow: inset 0 0 10px rgba(0,0,0,0.05);
}

/* Front side (right page) */
.front {
    border-left: 1px solid rgba(0,0,0,0.1);
    border-radius: 0 5px 5px 0;
}

/* Back side (left page) */
.back {
    transform: rotateY(180deg);
    border-right: 1px solid rgba(0,0,0,0.1);
    border-radius: 5px 0 0 5px;
}

/* Center binding shadows */
.front::after {
    content: "";
    position: absolute;
    top: 0; left: 0; bottom: 0; width: 10%;
    background: linear-gradient(to right, rgba(0,0,0,0.15), rgba(0,0,0,0));
    pointer-events: none;
}

.back::after {
    content: "";
    position: absolute;
    top: 0; right: 0; bottom: 0; width: 10%;
    background: linear-gradient(to left, rgba(0,0,0,0.15), rgba(0,0,0,0));
    pointer-events: none;
}

/* Flipped leaf */
.leaf.flipped {
    transform: rotateY(-180deg);
}

.zoom-controls-pill {
    position: fixed;
    bottom: 25px;
    left: 25px;
    transform: translateZ(100px);
    display: flex;
    align-items: center;
    background: rgba(255, 255, 255, 0.75);
    backdrop-filter: blur(25px);
    border: 1px solid rgba(255,255,255,0.8);
    border-radius: 29px;
    padding: 0;
    box-shadow: 0 8px 30px rgba(0,0,0,0.1);
    z-index: 1000;
    gap: 0;
    overflow: hidden;
}

.zoom-divider {
    width: 1px;
    height: 24px;
    background: rgba(0, 0, 0, 0.15);
}

.menu-toggle-btn {
    position: fixed;
    bottom: 25px;
    right: 25px;
    width: 50px;
    height: 50px;
    border-radius: 50%;
    background: rgba(255, 255, 255, 0.75);
    backdrop-filter: blur(25px);
    box-shadow: 0 8px 30px rgba(0,0,0,0.15);
    border: 1px solid rgba(255,255,255,0.8);
    z-index: 1000;
    color: #333;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s;
    user-select: none;
    touch-action: manipulation;
}

.menu-toggle-btn:hover {
    background: rgba(255, 255, 255, 0.95);
    transform: scale(1.05);
}

.menu-toggle-btn:active {
    transform: scale(0.95);
}

.slider-menu-container {
    position: fixed;
    bottom: 85px;
    right: 25px;
    background: rgba(255, 255, 255, 0.85);
    backdrop-filter: blur(25px);
    border: 1px solid rgba(255,255,255,0.8);
    border-radius: 16px;
    padding: 15px;
    width: 250px;
    box-shadow: 0 8px 30px rgba(0,0,0,0.15);
    z-index: 999;
    transform: translateY(20px);
    opacity: 0;
    pointer-events: none;
    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

.slider-menu-container.show {
    transform: translateY(0);
    opacity: 1;
    pointer-events: auto;
}

.slider-menu-content {
    display: flex;
    flex-direction: column;
    gap: 15px;
}

.nav-btn {
    position: fixed;
    bottom: 95px;
    width: 48px;
    height: 64px;
    border: none;
    background: rgba(255, 255, 255, 0.55);
    backdrop-filter: blur(12px);
    color: #444;
    font-size: 1.1rem;
    cursor: pointer;
    box-shadow: 0 4px 20px rgba(0,0,0,0.08);
    transition: background 0.2s, transform 0.15s, opacity 0.2s;
    display: flex;
    justify-content: center;
    align-items: center;
    user-select: none;
    z-index: 900;
    border: 1px solid rgba(255,255,255,0.7);
}

.nav-btn-left {
    left: 0;
    border-radius: 0 16px 16px 0;
    padding-left: 4px;
}

.nav-btn-right {
    right: 0;
    border-radius: 16px 0 0 16px;
    padding-right: 4px;
}

.nav-btn:hover {
    background: rgba(255, 255, 255, 0.85);
}

.nav-btn:active {
    background: #ddecea;
}

.nav-btn:disabled {
    opacity: 0.15;
    cursor: not-allowed;
}

.zoom-btn {
    width: 50px;
    height: 48px;
    border-radius: 0;
    background: transparent;
    border: none;
    color: #333;
    font-size: 1.6rem;
    font-weight: bold;
    cursor: pointer;
    transition: background 0.2s, color 0.2s;
    display: flex;
    justify-content: center;
    align-items: center;
    user-select: none;
    line-height: 0;
    padding-bottom: 3px;
}

.zoom-btn:hover {
    background: rgba(0, 0, 0, 0.05);
}

.zoom-btn:active {
    background: rgba(0, 0, 0, 0.1);
}

.zoom-btn:disabled {
    opacity: 0.3;
    cursor: not-allowed;
    transform: none;
}

.page-indicator {
    font-size: 0.95rem;
    font-weight: 600;
    color: #333333;
    background: rgba(255, 255, 255, 0.5);
    padding: 6px 12px;
    border-radius: 8px;
    text-align: center;
    box-shadow: 0 2px 5px rgba(0,0,0,0.02);
}

.slider-wrapper {
    display: flex;
    align-items: center;
    width: 100%;
}

input[type=range] {
    -webkit-appearance: none;
    width: 100%;
    background: transparent;
}

input[type=range]::-webkit-slider-runnable-track {
    width: 100%;
    height: 6px;
    cursor: pointer;
    background: rgba(0, 0, 0, 0.08);
    border-radius: 3px;
    box-shadow: inset 0 1px 3px rgba(0,0,0,0.05);
}

input[type=range]::-webkit-slider-thumb {
    -webkit-appearance: none;
    height: 20px;
    width: 20px;
    border-radius: 50%;
    background: #ffffff;
    cursor: pointer;
    margin-top: -7px;
    box-shadow: 0 0 10px rgba(0,0,0,0.15), 0 0 0 3px rgba(0,0,0,0.03);
    transition: transform 0.2s, box-shadow 0.2s;
}

input[type=range]::-webkit-slider-thumb:hover {
    transform: scale(1.15);
    box-shadow: 0 0 15px rgba(0,0,0,0.2), 0 0 0 5px rgba(0,0,0,0.06);
}

input[type=range]:focus {
    outline: none;
}
""".replace("ASPECT_RATIO_PLACEHOLDER", f"{aspect_ratio:.4f}")

    # JS content
    js_content = """document.addEventListener("DOMContentLoaded", () => {
    const leaves = document.querySelectorAll('.leaf');
    const slider = document.getElementById('pageSlider');
    const pageIndicator = document.getElementById('pageIndicator');
    const totalPages = PAGE_COUNT_PLACEHOLDER;
    
    let currentFlipped = 0;
    
    const bookEl = document.querySelector('.book');
    leaves.forEach((leaf, i) => {
        leaf.style.zIndex = leaves.length - i;
    });

    // Page turning by clicking on the page is disabled.

    // Menu toggle
    const menuToggleBtn = document.getElementById('menuToggleBtn');
    const sliderMenu = document.getElementById('sliderMenu');
    
    if (menuToggleBtn && sliderMenu) {
        menuToggleBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            sliderMenu.classList.toggle('show');
        });
        
        // Close the menu when clicking outside it.
        document.addEventListener('click', (e) => {
            if (sliderMenu.classList.contains('show') && !sliderMenu.contains(e.target) && e.target !== menuToggleBtn) {
                sliderMenu.classList.remove('show');
            }
        });
        
        // Keep slider clicks from bubbling up to the document.
        sliderMenu.addEventListener('click', (e) => {
            e.stopPropagation();
        });
    }

    // Swipe and zoom/pan support
    let touchStartX = 0, touchEndX = 0;
    let lastTouchTime = 0; // iOS Safari double-tap zoom limiter
    
    // Zoom/Pan Variables
    const zoomInBtn = document.getElementById('zoomInBtn');
    const zoomOutBtn = document.getElementById('zoomOutBtn');
    let currentZoom = 1.0;
    const MIN_ZOOM = 1.0;
    const MAX_ZOOM = 7.0;
    const ZOOM_STEP = 1.0;
    let panX = 0, panY = 0;
    let dragStartX = 0, dragStartY = 0;
    let lastPanX = 0, lastPanY = 0;
    let isDragging = false;
    let dragMoved = false; // Distinguish clicks from drags.

    // Pinch Variables
    let initialPinchDistance = null;
    let initialZoom = 1.0;

    function getDistance(touches) {
        return Math.hypot(touches[0].clientX - touches[1].clientX, touches[0].clientY - touches[1].clientY);
    }
    
    function getCenter(touches) {
        return {
            x: (touches[0].clientX + touches[1].clientX) / 2,
            y: (touches[0].clientY + touches[1].clientY) / 2
        };
    }

    // Navigation buttons
    const prevBtn = document.getElementById('prevBtn');
    const nextBtn = document.getElementById('nextBtn');
    if (prevBtn) prevBtn.addEventListener('click', () => goToLeaf(currentFlipped - 1));
    if (nextBtn) nextBtn.addEventListener('click', () => goToLeaf(currentFlipped + 1));

    function updateNavButtons() {
        if (prevBtn) prevBtn.disabled = currentFlipped <= 0;
        if (nextBtn) nextBtn.disabled = currentFlipped >= leaves.length;
    }

    // Update zoom button states.
    function updateZoomButtons() {
        if (zoomInBtn)  zoomInBtn.disabled  = currentZoom >= MAX_ZOOM;
        if (zoomOutBtn) zoomOutBtn.disabled = currentZoom <= MIN_ZOOM;
    }

    let lastVRAMKey = '';
    function manageVRAM(targetLeaf) {
        const mode = currentZoom > MIN_ZOOM ? 'zoom' : 'normal';
        const vramKey = `${mode}:${targetLeaf}`;
        if (vramKey === lastVRAMKey) return;
        lastVRAMKey = vramKey;

        if (currentZoom > MIN_ZOOM) {
            // Keep only the current two sides in the DOM while zoomed in.
            leaves.forEach((leaf, i) => {
                if (i === targetLeaf || i === targetLeaf - 1) {
                    leaf.style.display = 'block';
                } else {
                    leaf.style.display = 'none';
                }
            });
        } else {
            // At 1x, keep only nearby leaves in the DOM to avoid freezes.
            leaves.forEach((leaf, i) => {
                if (Math.abs(i - targetLeaf) <= 3) {
                    leaf.style.display = 'block';
                } else {
                    leaf.style.display = 'none';
                }
            });
        }
    }

    function clamp(value, min, max) {
        return Math.max(min, Math.min(max, value));
    }

    // Batch zoom/pan updates into one frame for smoother mobile rendering.
    let renderQueued = false;
    let renderImmediate = false;
    function scheduleApplyZoomAndPan(immediate = false) {
        renderImmediate = renderImmediate || immediate;
        if (renderQueued) return;
        renderQueued = true;
        requestAnimationFrame(() => {
            renderQueued = false;
            applyZoomAndPan(renderImmediate);
            renderImmediate = false;
        });
    }

    // Zoom engine
    function applyZoomAndPan(immediate = false) {
        manageVRAM(currentFlipped);
        let baseHeightCalc = (window.innerHeight < 500 && window.innerWidth > window.innerHeight) ? "(100dvh - 85px)" : "(100dvh - 130px)";
        
        if (currentZoom === MIN_ZOOM) {
            panX = 0; panY = 0;
            bookEl.style.width = '';
            bookEl.style.maxWidth = '';
            bookEl.style.transform = '';
            bookEl.style.willChange = 'auto';
            if (immediate) {
                bookEl.style.transition = 'none';
            } else {
                bookEl.style.transition = 'width 0.2s, max-width 0.2s, transform 0.2s ease';
                setTimeout(() => bookEl.style.transition = '', 200);
            }
        } else {
            bookEl.style.willChange = 'width, max-width, transform';
            bookEl.style.width = `calc(95vw * ${currentZoom})`;
            bookEl.style.maxWidth = `calc(${baseHeightCalc} * ASPECT_RATIO_PLACEHOLDER * ${currentZoom})`;
            bookEl.style.transform = `translate3d(${panX}px, ${panY}px, 0)`;
            bookEl.style.transition = immediate ? 'none' : 'width 0.2s, max-width 0.2s, transform 0.12s ease-out';
        }
        updateZoomButtons(); // Update disabled states.
    }

    if (zoomInBtn) {
        zoomInBtn.addEventListener('click', () => {
            if (currentZoom < MAX_ZOOM) {
                currentZoom = clamp(currentZoom + ZOOM_STEP, MIN_ZOOM, MAX_ZOOM);
                scheduleApplyZoomAndPan();
            }
        });
    }

    if (zoomOutBtn) {
        zoomOutBtn.addEventListener('click', () => {
            if (currentZoom > MIN_ZOOM) {
                currentZoom = clamp(currentZoom - ZOOM_STEP, MIN_ZOOM, MAX_ZOOM);
                scheduleApplyZoomAndPan();
            }
        });
    }

    function handleSwipe() {
        let swipeDistance = touchStartX - touchEndX;
        if (Math.abs(swipeDistance) > 40) {
            if (swipeDistance > 0) goToLeaf(currentFlipped + 1);
            else goToLeaf(currentFlipped - 1);
        }
    }

    // Global iOS Safari double-tap and pinch-zoom limiter
    // Prevent double-tap zoom unless the user is tapping buttons.
    document.addEventListener('touchstart', (e) => {
        if (e.touches.length > 1) {
            if (e.cancelable) e.preventDefault();
            return;
        }
        const now = new Date().getTime();
        if (now - lastTouchTime <= 300) {
            const tag = e.target.tagName;
            // Block double-tap zoom outside buttons and inputs.
            if (tag !== 'BUTTON' && tag !== 'INPUT') {
                if (e.cancelable) e.preventDefault();
            } 
            // Still block it for disabled controls.
            else if (e.target.disabled) {
                if (e.cancelable) e.preventDefault();
            }
        }
        lastTouchTime = now;
    }, {passive: false});

    // Shared drag handlers
    function handleDragStart(e) {
        if (e.touches && e.touches.length === 2) {
            isDragging = false;
            initialPinchDistance = getDistance(e.touches);
            initialZoom = currentZoom;
            return;
        }

        isDragging = true;
        dragMoved = false; // Reset on every new drag.
        let clientX = e.touches ? e.touches[0].clientX : e.clientX;
        let clientY = e.touches ? e.touches[0].clientY : e.clientY;
        touchStartX = clientX;
        dragStartX = clientX;
        dragStartY = clientY;
        lastPanX = panX;
        lastPanY = panY;
    }

    function handleActiveDrag(e) {
        if (e.touches && e.touches.length === 2) {
            if (e.cancelable) e.preventDefault();
            if (initialPinchDistance) {
                let currentDistance = getDistance(e.touches);
                let scaleChange = currentDistance / initialPinchDistance;
                let newZoom = initialZoom * scaleChange;
                
                newZoom = clamp(newZoom, MIN_ZOOM, MAX_ZOOM);
                
                let center = getCenter(e.touches);
                let ratio = newZoom / currentZoom;
                
                if (ratio !== 1 && currentZoom > 0) {
                    panX = panX * ratio - (center.x - window.innerWidth/2) * (ratio - 1);
                    panY = panY * ratio - (center.y - window.innerHeight/2) * (ratio - 1);
                }
                
                currentZoom = newZoom;
                scheduleApplyZoomAndPan(true);
            }
            return;
        }

        if (!isDragging) return;
        if (currentZoom > MIN_ZOOM) {
            // When zoomed in, block swipe and pan the image instead.
            let clientX = e.touches ? e.touches[0].clientX : e.clientX;
            let clientY = e.touches ? e.touches[0].clientY : e.clientY;
            let deltaX = clientX - dragStartX;
            let deltaY = clientY - dragStartY;
            if (Math.abs(deltaX) > 3 || Math.abs(deltaY) > 3) dragMoved = true;
            panX = lastPanX + deltaX;
            panY = lastPanY + deltaY;
            scheduleApplyZoomAndPan(true);
        } else {
            // In normal mode, treat movement over 5px as a drag.
            let clientX = e.touches ? e.touches[0].clientX : e.clientX;
            if (Math.abs(clientX - dragStartX) > 5) dragMoved = true;
        }
    }

    function handleDragEnd(e) {
        initialPinchDistance = null; // Reset pinch
        if (!isDragging) return;
        isDragging = false;
        let clientX = e.changedTouches ? e.changedTouches[0].clientX : e.clientX;
        touchEndX = clientX;
        
        // Only run swipe behavior at the default zoom level.
        if (currentZoom === MIN_ZOOM) {
            handleSwipe();
        }
    }

    // Event listeners for mobile and desktop. passive:false is needed for Safari gesture control.
    bookEl.addEventListener('touchstart', handleDragStart, {passive: false});
    bookEl.addEventListener('touchmove', handleActiveDrag, {passive: false});
    bookEl.addEventListener('touchend', handleDragEnd, {passive: false});
    
    bookEl.addEventListener('mousedown', handleDragStart);
    bookEl.addEventListener('mousemove', handleActiveDrag);
    bookEl.addEventListener('mouseup', handleDragEnd);
    bookEl.addEventListener('mouseleave', () => { isDragging = false; });
    bookEl.addEventListener('dblclick', (e) => { e.preventDefault(); }); // Block desktop double-click zoom.
    
    if (slider) {
        // While dragging the slider, update only the page indicator.
        slider.addEventListener('input', (e) => {
            let tempLeaf = Math.floor((parseInt(e.target.value) + 1) / 2);
            updateIndicator(tempLeaf);
        });
        
        // When the slider is released, animate once to the target page.
        slider.addEventListener('change', (e) => {
            let finalLeaf = Math.floor((parseInt(e.target.value) + 1) / 2);
            goToLeaf(finalLeaf);
        });
    }
    
    function updateIndicator(val) {
        if (!pageIndicator) return;
        let leftPage = val * 2;
        let rightPage = val * 2 + 1;
        let text = "";
        
        if (val === 0) {
            text = "PAGE_LABEL_PLACEHOLDER 1 / " + totalPages;
        } else if (val === leaves.length) {
            if (leftPage > totalPages) leftPage = totalPages;
            text = "PAGE_LABEL_PLACEHOLDER " + leftPage + " / " + totalPages;
        } else {
            if (rightPage > totalPages) rightPage = totalPages;
            text = "PAGE_LABEL_PLACEHOLDER " + leftPage + " - " + rightPage + " / " + totalPages;
        }
        pageIndicator.textContent = text;
    }
    
    function goToLeaf(target) {
        if (target < 0) target = 0;
        if (target > leaves.length) target = leaves.length;
        if (target === currentFlipped) return;

        // Reset zoom instantly before page transitions.
        if (currentZoom !== MIN_ZOOM) {
            currentZoom = MIN_ZOOM;
            panX = 0; panY = 0;
            manageVRAM(target);
            bookEl.style.transition = 'none'; // Instant, no animation.
            bookEl.style.width = '';
            bookEl.style.maxWidth = '';
            bookEl.style.transform = '';
            updateZoomButtons();
            // Restore transitions on the next frame before the 3D flip.
            requestAnimationFrame(() => { bookEl.style.transition = ''; });
            
            // If navigation is pressed while zoomed in, exit zoom without turning the page.
            if(slider) {
                if (currentFlipped === 0) slider.value = 0;
                else if (currentFlipped === leaves.length) slider.value = totalPages;
                else slider.value = currentFlipped * 2;
                updateIndicator(currentFlipped);
            }
            return; // Cancel turning; the next click will turn the page.
        }
        
        manageVRAM(target);

        // Avoid z-index races during quick consecutive jumps.
        leaves.forEach((leaf, i) => {
            if (i < target) {
                if (!leaf.classList.contains('flipped')) {
                    if (leaf.zIndexTimer) clearTimeout(leaf.zIndexTimer);
                    leaf.style.zIndex = leaves.length + 20 + i; 
                    leaf.classList.add('flipped');
                    leaf.zIndexTimer = setTimeout(() => { leaf.style.zIndex = i + 1; }, 400);
                }
            } else {
                if (leaf.classList.contains('flipped')) {
                    if (leaf.zIndexTimer) clearTimeout(leaf.zIndexTimer);
                    leaf.style.zIndex = leaves.length + 20 + (leaves.length - i);
                    leaf.classList.remove('flipped');
                    leaf.zIndexTimer = setTimeout(() => { leaf.style.zIndex = leaves.length - i; }, 400);
                }
            }
        });
        
        currentFlipped = target;
        if(slider) {
            if (target === 0) slider.value = 0;
            else if (target === leaves.length) slider.value = totalPages;
            else slider.value = target * 2;
        }
        updateIndicator(currentFlipped);
        updateNavButtons();
    }
    
    updateIndicator(0);
    updateZoomButtons(); // Set initial button states.
    updateNavButtons();
});
""".replace("PAGE_COUNT_PLACEHOLDER", str(page_count)).replace("PAGE_LABEL_PLACEHOLDER", texts["page_word"]).replace("ASPECT_RATIO_PLACEHOLDER", f"{aspect_ratio:.4f}")

    with open(os.path.join(output_dir, "index.html"), "w", encoding="utf-8") as f:
        f.write(html_content)
        
    with open(os.path.join(output_dir, "style.css"), "w", encoding="utf-8") as f:
        f.write(css_content)
        
    with open(os.path.join(output_dir, "script.js"), "w", encoding="utf-8") as f:
        f.write(js_content)

if __name__ == "__main__":
    root = tk.Tk()
    app = PDFFlipbookGeneratorApp(root)
    root.mainloop()
